USE mmop_tesla_project;

CREATE EXTERNAL TABLE IF NOT EXISTS stock (s STRING,
p FLOAT, t STRING, v FLOAT, c STRING)
PARTITIONED BY(ingestion_date string)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS PARQUET
LOCATION '/user/mmop/stock';
